# This file is generated by rules_pycross.
# It is not intended for manual editing.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@jvolkman_rules_pycross//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library", "pypi_file")

PINS = {
    "grpclib": "grpclib_0.4.6",
    "h2": "h2_4.1.0",
    "hpack": "hpack_4.0.0",
    "hyperframe": "hyperframe_6.0.1",
    "multidict": "multidict_6.0.4",
    "setuptools": "setuptools_59.2.0",
    "wheel": "wheel_0.37.0",
}

def targets():
    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
        )

    native.config_setting(
        name = "_env_python_darwin_arm64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:aarch64",
        ],
    )

    native.config_setting(
        name = "_env_python_darwin_x86_64",
        constraint_values = [
            "@platforms//os:osx",
            "@platforms//cpu:x86_64",
        ],
    )

    native.config_setting(
        name = "_env_python_linux_x86_64",
        constraint_values = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    )

    _target = select({
        ":_env_python_darwin_arm64": "@//:python_darwin_arm64",
        ":_env_python_darwin_x86_64": "@//:python_darwin_x86_64",
        ":_env_python_linux_x86_64": "@//:python_linux_x86_64",
    })

    _grpclib_0_4_6_deps = [
        ":h2_4.1.0",
        ":multidict_6.0.4",
    ]

    _grpclib_0_4_6_build_deps = [
        ":setuptools_59.2.0",
        ":wheel_0.37.0",
    ]

    pycross_wheel_build(
        name = "_build_grpclib_0.4.6",
        sdist = "@example_lock_rules_python_sdist_grpclib_0.4.6//file",
        target_environment = _target,
        deps = _grpclib_0_4_6_deps + _grpclib_0_4_6_build_deps,
        tags = ["manual"],
    )

    pycross_wheel_library(
        name = "grpclib_0.4.6",
        deps = _grpclib_0_4_6_deps,
        wheel = ":_build_grpclib_0.4.6",
    )

    _h2_4_1_0_deps = [
        ":hpack_4.0.0",
        ":hyperframe_6.0.1",
    ]

    pycross_wheel_library(
        name = "h2_4.1.0",
        deps = _h2_4_1_0_deps,
        wheel = "@example_lock_rules_python_wheel_h2_4.1.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "hpack_4.0.0",
        wheel = "@example_lock_rules_python_wheel_hpack_4.0.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "hyperframe_6.0.1",
        wheel = "@example_lock_rules_python_wheel_hyperframe_6.0.1_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "multidict_6.0.4",
        wheel = select({
            ":_env_python_darwin_arm64": "@example_lock_rules_python_wheel_multidict_6.0.4_cp39_cp39_macosx_11_0_arm64//file",
            ":_env_python_darwin_x86_64": "@example_lock_rules_python_wheel_multidict_6.0.4_cp39_cp39_macosx_10_9_x86_64//file",
            ":_env_python_linux_x86_64": "@example_lock_rules_python_wheel_multidict_6.0.4_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64//file",
        }),
    )

    pycross_wheel_library(
        name = "setuptools_59.2.0",
        wheel = "@example_lock_rules_python_wheel_setuptools_59.2.0_py3_none_any//file",
    )

    pycross_wheel_library(
        name = "wheel_0.37.0",
        wheel = "@example_lock_rules_python_wheel_wheel_0.37.0_py2.py3_none_any//file",
    )

def repositories():
    maybe(
        http_file,
        name = "example_lock_rules_python_sdist_grpclib_0.4.6",
        urls = [
            "https://files.pythonhosted.org/packages/55/80/66d4b36161996e75166f752408bb82eb04aeabcfdb487c5fd8dace72491a/grpclib-0.4.6.tar.gz"
        ],
        sha256 = "595d05236ca8b8f8e433f5bf6095e6354c1d8777d003ddaf5288efa9611e3fd6",
        downloaded_file_path = "grpclib-0.4.6.tar.gz",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_h2_4.1.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/2a/e5/db6d438da759efbb488c4f3fbdab7764492ff3c3f953132efa6b9f0e9e53/h2-4.1.0-py3-none-any.whl"
        ],
        sha256 = "03a46bcf682256c95b5fd9e9a99c1323584c3eec6440d379b9903d709476bc6d",
        downloaded_file_path = "h2-4.1.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_hpack_4.0.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d5/34/e8b383f35b77c402d28563d2b8f83159319b509bc5f760b15d60b0abf165/hpack-4.0.0-py3-none-any.whl"
        ],
        sha256 = "84a076fad3dc9a9f8063ccb8041ef100867b1878b25ef0ee63847a5d53818a6c",
        downloaded_file_path = "hpack-4.0.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_hyperframe_6.0.1_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/d7/de/85a784bcc4a3779d1753a7ec2dee5de90e18c7bcf402e71b51fcf150b129/hyperframe-6.0.1-py3-none-any.whl"
        ],
        sha256 = "0ec6bafd80d8ad2195c4f03aacba3a8265e57bc4cff261e802bf39970ed02a15",
        downloaded_file_path = "hyperframe-6.0.1-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_multidict_6.0.4_cp39_cp39_macosx_10_9_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/f0/c1/de389de822e8442717e7fda86496a47af8a132104e1601f3419d26dff334/multidict-6.0.4-cp39-cp39-macosx_10_9_x86_64.whl"
        ],
        sha256 = "bc779e9e6f7fda81b3f9aa58e3a6091d49ad528b11ed19f6621408806204ad35",
        downloaded_file_path = "multidict-6.0.4-cp39-cp39-macosx_10_9_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_multidict_6.0.4_cp39_cp39_macosx_11_0_arm64",
        urls = [
            "https://files.pythonhosted.org/packages/dd/bd/cce218536b377efbee70d8680a97fd282f4e1e9f7ebff95c4ea28deef87a/multidict-6.0.4-cp39-cp39-macosx_11_0_arm64.whl"
        ],
        sha256 = "4ceef517eca3e03c1cceb22030a3e39cb399ac86bff4e426d4fc6ae49052cc60",
        downloaded_file_path = "multidict-6.0.4-cp39-cp39-macosx_11_0_arm64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_multidict_6.0.4_cp39_cp39_manylinux_2_17_x86_64.manylinux2014_x86_64",
        urls = [
            "https://files.pythonhosted.org/packages/69/48/2750fd3ace4d778b4e1f7110db3ad637906de3496abc9c450ce726b97337/multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        ],
        sha256 = "d5e3fc56f88cc98ef8139255cf8cd63eb2c586531e43310ff859d6bb3a6b51f1",
        downloaded_file_path = "multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_setuptools_59.2.0_py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/18/ad/ec41343a49a0371ea40daf37b1ba2c11333cdd121cb378161635d14b9750/setuptools-59.2.0-py3-none-any.whl"
        ],
        sha256 = "4adde3d1e1c89bde1c643c64d89cdd94cbfd8c75252ee459d4500bccb9c7d05d",
        downloaded_file_path = "setuptools-59.2.0-py3-none-any.whl",
    )

    maybe(
        http_file,
        name = "example_lock_rules_python_wheel_wheel_0.37.0_py2.py3_none_any",
        urls = [
            "https://files.pythonhosted.org/packages/04/80/cad93b40262f5d09f6de82adbee452fd43cdff60830b56a74c5930f7e277/wheel-0.37.0-py2.py3-none-any.whl"
        ],
        sha256 = "21014b2bd93c6d0034b6ba5d35e4eb284340e09d63c59aef6fc14b0f346146fd",
        downloaded_file_path = "wheel-0.37.0-py2.py3-none-any.whl",
    )

